package org.weso.sor.model;

// Generated Jan 24, 2009 2:26:38 PM by Hibernate Tools 3.2.4.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Guardian generated by hbm2java
 */
@Entity
@Table(name = "guardian", catalog = "weso", uniqueConstraints = @UniqueConstraint(columnNames = "user_name"))
public class Guardian implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8872353304466404422L;
	private Integer guardianId;
	private String userName;
	private String lastName;
	private String firstName;
	private String password;
	private Date dateCreated;
	private String primaryEmailAddress;
	private String secondaryEmailAddress;
	private String primaryPhoneNumber;
	private String secondaryPhoneNumber;
	private boolean photoPermisson;
	private String TShirtSize;
	private Set<StudentToGuardian> studentToGuardians = new HashSet<StudentToGuardian>(
			0);
	private Set<GuardianVolunteerChoices> guardianVolunteerChoiceses = new HashSet<GuardianVolunteerChoices>(
			0);
	private Set<GuardianEventChoices> guardianEventChoiceses = new HashSet<GuardianEventChoices>(
			0);

	public Guardian() {
	}

	public Guardian(String userName, String lastName, String firstName,
			String primaryEmailAddress,
			String primaryPhoneNumber, boolean photoPermisson, String TShirtSize) {
		this.userName = userName;
		this.lastName = lastName;
		this.firstName = firstName;
		this.dateCreated = new Date();
		this.primaryEmailAddress = primaryEmailAddress;
		this.primaryPhoneNumber = primaryPhoneNumber;
		this.photoPermisson = photoPermisson;
		this.TShirtSize = TShirtSize;
	}

	public Guardian(String userName, String lastName, String firstName,
			String password, Date dateCreated, String primaryEmailAddress,
			String secondaryEmailAddress, String primaryPhoneNumber,
			String secondaryPhoneNumber, boolean photoPermisson,
			String TShirtSize, Set<StudentToGuardian> studentToGuardians,
			Set<GuardianVolunteerChoices> guardianVolunteerChoiceses,
			Set<GuardianEventChoices> guardianEventChoiceses) {
		this.userName = userName;
		this.lastName = lastName;
		this.firstName = firstName;
		this.password = password;
		this.dateCreated = dateCreated;
		this.primaryEmailAddress = primaryEmailAddress;
		this.secondaryEmailAddress = secondaryEmailAddress;
		this.primaryPhoneNumber = primaryPhoneNumber;
		this.secondaryPhoneNumber = secondaryPhoneNumber;
		this.photoPermisson = photoPermisson;
		this.TShirtSize = TShirtSize;
		this.studentToGuardians = studentToGuardians;
		this.guardianVolunteerChoiceses = guardianVolunteerChoiceses;
		this.guardianEventChoiceses = guardianEventChoiceses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "guardian_id", unique = true, nullable = false)
	public Integer getGuardianId() {
		return this.guardianId;
	}

	public void setGuardianId(Integer guardianId) {
		this.guardianId = guardianId;
	}

	@Column(name = "user_name", unique = true, nullable = false, length = 64)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "last_name", nullable = false, length = 64)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "first_name", nullable = false, length = 64)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "password", length = 30)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_created", nullable = false, length = 19)
	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	@Column(name = "primary_email_address", nullable = false, length = 64)
	public String getPrimaryEmailAddress() {
		return this.primaryEmailAddress;
	}

	public void setPrimaryEmailAddress(String primaryEmailAddress) {
		this.primaryEmailAddress = primaryEmailAddress;
	}

	@Column(name = "secondary_email_address", length = 64)
	public String getSecondaryEmailAddress() {
		return this.secondaryEmailAddress;
	}

	public void setSecondaryEmailAddress(String secondaryEmailAddress) {
		this.secondaryEmailAddress = secondaryEmailAddress;
	}

	@Column(name = "primary_phone_number", nullable = false, length = 12)
	public String getPrimaryPhoneNumber() {
		return this.primaryPhoneNumber;
	}

	public void setPrimaryPhoneNumber(String primaryPhoneNumber) {
		this.primaryPhoneNumber = primaryPhoneNumber;
	}

	@Column(name = "secondary_phone_number", length = 12)
	public String getSecondaryPhoneNumber() {
		return this.secondaryPhoneNumber;
	}

	public void setSecondaryPhoneNumber(String secondaryPhoneNumber) {
		this.secondaryPhoneNumber = secondaryPhoneNumber;
	}

	@Column(name = "photo_permisson", nullable = false)
	public boolean isPhotoPermisson() {
		return this.photoPermisson;
	}

	public void setPhotoPermisson(boolean photoPermisson) {
		this.photoPermisson = photoPermisson;
	}

	@Column(name = "t_shirt_size", nullable = false, length = 24)
	public String getTShirtSize() {
		return this.TShirtSize;
	}

	public void setTShirtSize(String TShirtSize) {
		this.TShirtSize = TShirtSize;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "guardian")
	public Set<StudentToGuardian> getStudentToGuardians() {
		return this.studentToGuardians;
	}

	public void setStudentToGuardians(Set<StudentToGuardian> studentToGuardians) {
		this.studentToGuardians = studentToGuardians;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "guardian")
	public Set<GuardianVolunteerChoices> getGuardianVolunteerChoiceses() {
		return this.guardianVolunteerChoiceses;
	}

	public void setGuardianVolunteerChoiceses(
			Set<GuardianVolunteerChoices> guardianVolunteerChoiceses) {
		this.guardianVolunteerChoiceses = guardianVolunteerChoiceses;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "guardian")
	public Set<GuardianEventChoices> getGuardianEventChoiceses() {
		return this.guardianEventChoiceses;
	}

	public void setGuardianEventChoiceses(
			Set<GuardianEventChoices> guardianEventChoiceses) {
		this.guardianEventChoiceses = guardianEventChoiceses;
	}

}
