package org.weso.sor.model;

// Generated Jan 24, 2009 2:26:38 PM by Hibernate Tools 3.2.4.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * GuardianEventChoices generated by hbm2java
 */
@Entity
@Table(name = "guardian_event_choices", catalog = "weso", uniqueConstraints = {
		@UniqueConstraint(columnNames = { "pec_guardian_id", "pec_events_id" }),
		@UniqueConstraint(columnNames = { "pec_guardian_id", "ranking" }) })
public class GuardianEventChoices implements java.io.Serializable {

	private Integer guardianEventChoicesId;
	private Events events;
	private Guardian guardian;
	private int ranking;

	public GuardianEventChoices() {
	}

	public GuardianEventChoices(Events events, Guardian guardian, int ranking) {
		this.events = events;
		this.guardian = guardian;
		this.ranking = ranking;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "guardian_Event_Choices_id", unique = true, nullable = false)
	public Integer getGuardianEventChoicesId() {
		return this.guardianEventChoicesId;
	}

	public void setGuardianEventChoicesId(Integer guardianEventChoicesId) {
		this.guardianEventChoicesId = guardianEventChoicesId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pec_events_id", nullable = false)
	public Events getEvents() {
		return this.events;
	}

	public void setEvents(Events events) {
		this.events = events;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pec_guardian_id", nullable = false)
	public Guardian getGuardian() {
		return this.guardian;
	}

	public void setGuardian(Guardian guardian) {
		this.guardian = guardian;
	}

	@Column(name = "ranking", nullable = false)
	public int getRanking() {
		return this.ranking;
	}

	public void setRanking(int ranking) {
		this.ranking = ranking;
	}

}
