package org.weso.sor.model;

// Generated Jan 24, 2009 2:26:38 PM by Hibernate Tools 3.2.4.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * GuardianVolunteerChoices generated by hbm2java
 */
@Entity
@Table(name = "guardian_volunteer_choices", catalog = "weso", uniqueConstraints = {
		@UniqueConstraint(columnNames = { "pvc_guardian_id", "pvc_activity_id" }),
		@UniqueConstraint(columnNames = { "pvc_activity_id", "ranking" }) })
public class GuardianVolunteerChoices implements java.io.Serializable {

	private Integer id;
	private Guardian guardian;
	private VolunteerActivities volunteerActivities;
	private int ranking;

	public GuardianVolunteerChoices() {
	}

	public GuardianVolunteerChoices(Guardian guardian,
			VolunteerActivities volunteerActivities, int ranking) {
		this.guardian = guardian;
		this.volunteerActivities = volunteerActivities;
		this.ranking = ranking;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pvc_guardian_id", nullable = false)
	public Guardian getGuardian() {
		return this.guardian;
	}

	public void setGuardian(Guardian guardian) {
		this.guardian = guardian;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pvc_activity_id", nullable = false)
	public VolunteerActivities getVolunteerActivities() {
		return this.volunteerActivities;
	}

	public void setVolunteerActivities(VolunteerActivities volunteerActivities) {
		this.volunteerActivities = volunteerActivities;
	}

	@Column(name = "ranking", nullable = false)
	public int getRanking() {
		return this.ranking;
	}

	public void setRanking(int ranking) {
		this.ranking = ranking;
	}

}
