package org.weso.sor.model;

// Generated Jan 24, 2009 2:26:38 PM by Hibernate Tools 3.2.4.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Student generated by hbm2java
 */
@Entity
@Table(name = "student", catalog = "weso")
public class Student implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7438474390472623873L;
	private Integer studentId;
	private Teacher teacher;
	private Grade grade;
	private String lastName;
	private String firstName;
	private String phoneNumber;
	private String tshirtSize;
	private int numberOfEvents;
	private Date dateCreated;
	private Set<StudentEventChoices> studentEventChoiceses = new HashSet<StudentEventChoices>(
			0);
	private Set<StudentToGuardian> studentToGuardians = new HashSet<StudentToGuardian>(
			0);

	public Student() {
	}

	public Student(
			final Teacher teacher, 
			final Grade grade, 
			final String lastName,
			final String firstName, 
			final String phoneNumber, 
			final String tshirtSize,
			int numberOfEvents) {
		this.teacher = teacher;
		this.grade = grade;
		this.lastName = lastName;
		this.firstName = firstName;
		this.phoneNumber = phoneNumber;
		this.tshirtSize = tshirtSize;
		this.numberOfEvents = numberOfEvents;
		this.dateCreated = new Date();
	}

	public Student(Teacher teacher, Grade grade, String lastName,
			String firstName, String phoneNumber, String tshirtSize,
			int numberOfEvents, Date dateCreated,
			Set<StudentEventChoices> studentEventChoiceses,
			Set<StudentToGuardian> studentToGuardians) {
		this.teacher = teacher;
		this.grade = grade;
		this.lastName = lastName;
		this.firstName = firstName;
		this.phoneNumber = phoneNumber;
		this.tshirtSize = tshirtSize;
		this.numberOfEvents = numberOfEvents;
		this.dateCreated = dateCreated;
		this.studentEventChoiceses = studentEventChoiceses;
		this.studentToGuardians = studentToGuardians;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "student_id", unique = true, nullable = false)
	public Integer getStudentId() {
		return this.studentId;
	}

	public void setStudentId(Integer studentId) {
		this.studentId = studentId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "teacher", nullable = false)
	public Teacher getTeacher() {
		return this.teacher;
	}

	public void setTeacher(Teacher teacher) {
		this.teacher = teacher;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "grade", nullable = false)
	public Grade getGrade() {
		return this.grade;
	}

	public void setGrade(Grade grade) {
		this.grade = grade;
	}

	@Column(name = "last_name", nullable = false, length = 64)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "first_name", nullable = false, length = 64)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "phone_number", nullable = false, length = 12)
	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	@Column(name = "t_shirt_size", nullable = false, length = 24)
	public String getTshirtSize() {
		return this.tshirtSize;
	}

	public void setTshirtSize(String tshirtSize) {
		this.tshirtSize = tshirtSize;
	}

	@Column(name = "number_of_events", nullable = false)
	public int getNumberOfEvents() {
		return this.numberOfEvents;
	}

	public void setNumberOfEvents(int numberOfEvents) {
		this.numberOfEvents = numberOfEvents;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_created", nullable = false, length = 19)
	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "student")
	public Set<StudentEventChoices> getStudentEventChoiceses() {
		return this.studentEventChoiceses;
	}

	public void setStudentEventChoiceses(
			Set<StudentEventChoices> studentEventChoiceses) {
		this.studentEventChoiceses = studentEventChoiceses;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "student")
	public Set<StudentToGuardian> getStudentToGuardians() {
		return this.studentToGuardians;
	}

	public void setStudentToGuardians(Set<StudentToGuardian> studentToGuardians) {
		this.studentToGuardians = studentToGuardians;
	}

}
