package org.weso.sor.model;

//Generated Jan 28, 2009 9:16:19 PM by Hibernate Tools 3.2.4.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
* StudentEventChoices generated by hbm2java
*/
@Entity
@Table(name = "student_event_choices", catalog = "weso", uniqueConstraints = @UniqueConstraint(columnNames = {
		"sec_student_id", "sec_events_id" }))
public class StudentEventChoices implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7332234161657481715L;
	private Integer studentEventChoicesId;
	private Events events;
	private Student student;
	private int ranking;
	private Boolean alternate;

	public StudentEventChoices() {
	}

	public StudentEventChoices(Events events, Student student, int ranking) {
		this.events = events;
		this.student = student;
		this.ranking = ranking;
	}

	public StudentEventChoices(Events events, Student student, int ranking,
			Boolean alternate) {
		this.events = events;
		this.student = student;
		this.ranking = ranking;
		this.alternate = alternate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "student_Event_Choices_id", unique = true, nullable = false)
	public Integer getStudentEventChoicesId() {
		return this.studentEventChoicesId;
	}

	public void setStudentEventChoicesId(Integer studentEventChoicesId) {
		this.studentEventChoicesId = studentEventChoicesId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sec_events_id", nullable = false)
	public Events getEvents() {
		return this.events;
	}

	public void setEvents(Events events) {
		this.events = events;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sec_student_id", nullable = false)
	public Student getStudent() {
		return this.student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}

	@Column(name = "ranking", nullable = false)
	public int getRanking() {
		return this.ranking;
	}

	public void setRanking(int ranking) {
		this.ranking = ranking;
	}

	@Column(name = "alternate")
	public Boolean getAlternate() {
		return this.alternate;
	}

	public void setAlternate(Boolean alternate) {
		this.alternate = alternate;
	}

}
