package org.weso.sor.model;

// Generated Jan 24, 2009 2:26:38 PM by Hibernate Tools 3.2.4.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * TeacherToGrade generated by hbm2java
 */
@Entity
@Table(name = "teacher_to_grade", catalog = "weso", uniqueConstraints = @UniqueConstraint(columnNames = {
		"ttg_teacher_id", "ttg_grade_id" }))
public class TeacherToGrade implements java.io.Serializable {

	private Integer ttgId;
	private Grade grade;
	private Teacher teacher;

	public TeacherToGrade() {
	}

	public TeacherToGrade(Grade grade, Teacher teacher) {
		this.grade = grade;
		this.teacher = teacher;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ttg_id", unique = true, nullable = false)
	public Integer getTtgId() {
		return this.ttgId;
	}

	public void setTtgId(Integer ttgId) {
		this.ttgId = ttgId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ttg_grade_id", nullable = false)
	public Grade getGrade() {
		return this.grade;
	}

	public void setGrade(Grade grade) {
		this.grade = grade;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ttg_teacher_id", nullable = false)
	public Teacher getTeacher() {
		return this.teacher;
	}

	public void setTeacher(Teacher teacher) {
		this.teacher = teacher;
	}

}
