package org.weso.sor.model;

// Generated Jan 24, 2009 2:26:38 PM by Hibernate Tools 3.2.4.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Teacher generated by hbm2java
 */
@Entity
@Table(name = "teacher", catalog = "weso")
public class Teacher implements java.io.Serializable {

	private Integer teacherId;
	private String teacherName;
	private Set<TeacherToGrade> teacherToGrades = new HashSet<TeacherToGrade>(0);
	private Set<Student> students = new HashSet<Student>(0);

	public Teacher() {
	}

	public Teacher(String teacherName) {
		this.teacherName = teacherName;
	}

	public Teacher(String teacherName, Set<TeacherToGrade> teacherToGrades,
			Set<Student> students) {
		this.teacherName = teacherName;
		this.teacherToGrades = teacherToGrades;
		this.students = students;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "teacher_id", unique = true, nullable = false)
	public Integer getTeacherId() {
		return this.teacherId;
	}

	public void setTeacherId(Integer teacherId) {
		this.teacherId = teacherId;
	}

	@Column(name = "teacher_name", nullable = false, length = 64)
	public String getTeacherName() {
		return this.teacherName;
	}

	public void setTeacherName(String teacherName) {
		this.teacherName = teacherName;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "teacher")
	public Set<TeacherToGrade> getTeacherToGrades() {
		return this.teacherToGrades;
	}

	public void setTeacherToGrades(Set<TeacherToGrade> teacherToGrades) {
		this.teacherToGrades = teacherToGrades;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "teacher")
	public Set<Student> getStudents() {
		return this.students;
	}

	public void setStudents(Set<Student> students) {
		this.students = students;
	}

}
