package org.weso.sor.model;

// Generated Jan 24, 2009 2:26:38 PM by Hibernate Tools 3.2.4.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Events generated by hbm2java
 */
@Entity
@Table(name = "events", catalog = "weso", uniqueConstraints = @UniqueConstraint(columnNames = "event_name"))
public class Events implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7725423518071690421L;
	private Integer eventsId;
	private String eventName;
	private String description;
	private Set<GuardianEventChoices> guardianEventChoiceses = new HashSet<GuardianEventChoices>(
			0);
	private Set<StudentEventChoices> studentEventChoiceses = new HashSet<StudentEventChoices>(
			0);
	private Set<EventToGrade> eventToGrades = new HashSet<EventToGrade>(0);

	public Events() {
	}

	public Events(String eventName) {
		this.eventName = eventName;
	}

	public Events(String eventName, String description,
			Set<GuardianEventChoices> guardianEventChoiceses,
			Set<StudentEventChoices> studentEventChoiceses,
			Set<EventToGrade> eventToGrades) {
		this.eventName = eventName;
		this.description = description;
		this.guardianEventChoiceses = guardianEventChoiceses;
		this.studentEventChoiceses = studentEventChoiceses;
		this.eventToGrades = eventToGrades;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "events_id", unique = true, nullable = false)
	public Integer getEventsId() {
		return this.eventsId;
	}

	public void setEventsId(Integer eventsId) {
		this.eventsId = eventsId;
	}

	@Column(name = "event_name", unique = true, nullable = false, length = 64)
	public String getEventName() {
		return this.eventName;
	}

	public void setEventName(String eventName) {
		this.eventName = eventName;
	}

	@Column(name = "description", length = 1024)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "events")
	public Set<GuardianEventChoices> getGuardianEventChoiceses() {
		return this.guardianEventChoiceses;
	}

	public void setGuardianEventChoiceses(
			Set<GuardianEventChoices> guardianEventChoiceses) {
		this.guardianEventChoiceses = guardianEventChoiceses;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "events")
	public Set<StudentEventChoices> getStudentEventChoiceses() {
		return this.studentEventChoiceses;
	}

	public void setStudentEventChoiceses(
			Set<StudentEventChoices> studentEventChoiceses) {
		this.studentEventChoiceses = studentEventChoiceses;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "events")
	public Set<EventToGrade> getEventToGrades() {
		return this.eventToGrades;
	}

	public void setEventToGrades(Set<EventToGrade> eventToGrades) {
		this.eventToGrades = eventToGrades;
	}

}
