package org.weso.sor.model;

// Generated Jan 24, 2009 2:26:38 PM by Hibernate Tools 3.2.4.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * EventToGrade generated by hbm2java
 */
@Entity
@Table(name = "event_to_grade", catalog = "weso", uniqueConstraints = @UniqueConstraint(columnNames = {
		"etg_events_id", "etg_grade_id" }))
public class EventToGrade implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6593798381456764683L;
	private Integer etgId;
	private Grade grade;
	private Events events;

	public EventToGrade() {
	}

	public EventToGrade(Grade grade, Events events) {
		this.grade = grade;
		this.events = events;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "etg_id", unique = true, nullable = false)
	public Integer getEtgId() {
		return this.etgId;
	}

	public void setEtgId(Integer etgId) {
		this.etgId = etgId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "etg_grade_id", nullable = false)
	public Grade getGrade() {
		return this.grade;
	}

	public void setGrade(Grade grade) {
		this.grade = grade;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "etg_events_id", nullable = false)
	public Events getEvents() {
		return this.events;
	}

	public void setEvents(Events events) {
		this.events = events;
	}

}
