package org.weso.sor.model;

// Generated Jan 24, 2009 2:26:38 PM by Hibernate Tools 3.2.4.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Grade generated by hbm2java
 */
@Entity
@Table(name = "grade", catalog = "weso", uniqueConstraints = {
		@UniqueConstraint(columnNames = "grade_numb"),
		@UniqueConstraint(columnNames = "grade_desc") })
public class Grade implements java.io.Serializable {

	private Integer gradeId;
	private int gradeNumb;
	private String gradeDesc;
	private Set<TeacherToGrade> teacherToGrades = new HashSet<TeacherToGrade>(0);
	private Set<Student> students = new HashSet<Student>(0);
	private Set<EventToGrade> eventToGrades = new HashSet<EventToGrade>(0);

	public Grade() {
	}

	public Grade(int gradeNumb) {
		this.gradeNumb = gradeNumb;
	}

	public Grade(int gradeNumb, String gradeDesc,
			Set<TeacherToGrade> teacherToGrades, Set<Student> students,
			Set<EventToGrade> eventToGrades) {
		this.gradeNumb = gradeNumb;
		this.gradeDesc = gradeDesc;
		this.teacherToGrades = teacherToGrades;
		this.students = students;
		this.eventToGrades = eventToGrades;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "grade_id", unique = true, nullable = false)
	public Integer getGradeId() {
		return this.gradeId;
	}

	public void setGradeId(Integer gradeId) {
		this.gradeId = gradeId;
	}

	@Column(name = "grade_numb", unique = true, nullable = false)
	public int getGradeNumb() {
		return this.gradeNumb;
	}

	public void setGradeNumb(int gradeNumb) {
		this.gradeNumb = gradeNumb;
	}

	@Column(name = "grade_desc", unique = true, length = 32)
	public String getGradeDesc() {
		return this.gradeDesc;
	}

	public void setGradeDesc(String gradeDesc) {
		this.gradeDesc = gradeDesc;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "grade")
	public Set<TeacherToGrade> getTeacherToGrades() {
		return this.teacherToGrades;
	}

	public void setTeacherToGrades(Set<TeacherToGrade> teacherToGrades) {
		this.teacherToGrades = teacherToGrades;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "grade")
	public Set<Student> getStudents() {
		return this.students;
	}

	public void setStudents(Set<Student> students) {
		this.students = students;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "grade")
	public Set<EventToGrade> getEventToGrades() {
		return this.eventToGrades;
	}

	public void setEventToGrades(Set<EventToGrade> eventToGrades) {
		this.eventToGrades = eventToGrades;
	}

}
